name: TelescopeML
channels:
  - conda-forge
dependencies:
  - anyio=3.7.1
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - astropy=5.3.1
  - asttokens=2.2.1
  - async-lru=2.0.3
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - bokeh=3.2.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - comm=0.1.3
  - contourpy=1.1.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.2
  - executing=1.2.0
  - flit-core=3.9.0
  - fonttools=4.41.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - h5py=3.6.0
  - hdf5=1.12.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib-resources=6.0.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.0
  - ipykernel=6.25.0
  - ipython=8.14.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.7
  - isoduration=20.11.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.3.0
  - json5=0.9.14
  - jsonschema=4.18.4
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.18.4
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.1
  - jupyter_events=0.6.3
  - jupyter_server=2.7.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.24.0
  - jupyterlab_widgets=3.0.8
  - kiwisolver=1.4.4
  - krb5=1.21.1
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.2.1
  - libcxx=16.0.6
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.3.0
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libprotobuf=3.19.6
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mistune=3.0.0
  - munkres=1.1.4
  - nb_conda_kernels=2.3.1
  - nbclient=0.8.0
  - nbconvert=7.7.3
  - nbconvert-core=7.7.3
  - nbconvert-pandoc=7.7.3
  - nbformat=5.9.1
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=7.0.0
  - notebook-shim=0.2.3
  - openjpeg=2.5.0
  - openssl=3.1.4
  - overrides=7.3.1
  - packaging=23.1
  - pandas=2.0.3
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.0
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.9.1
  - pooch=1.7.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyerfa=2.0.0.3
  - pygments=2.15.1
  - pyobjc-core=9.2
  - pyobjc-framework-cocoa=9.2
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qtconsole-base=5.4.4
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.9.2
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - terminado=0.17.1
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - unicodedata2=15.0.0
  - uri-template=1.3.0
  - urllib3=2.0.7
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.1
  - wheel=0.41.0
  - widgetsnbextension=4.0.8
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.7.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - absl-py==2.0.0
      - alabaster==0.7.13
      - astunparse==1.6.3
      - cachetools==5.3.2
      - certifi==2023.11.17
      - docutils==0.20.1
      - flatbuffers==23.5.26
      - gast==0.5.4
      - google-auth==2.23.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.2
      - imagesize==1.4.1
      - jsonpointer==2.4
      - keras==2.14.0
      - libclang==16.0.6
      - markdown==3.5
      - ml-dtypes==0.2.0
      - numpy==1.26.1
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==4.24.4
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydot==1.4.2
      - graphviz==0.20.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - setuptools==69.0.0
      - snowballstemmer==2.2.0
      - spectres==2.2.0
      - sphinx==7.2.6
      - sphinxcontrib-applehelp==1.0.7
      - sphinxcontrib-devhelp==1.0.5
      - sphinxcontrib-htmlhelp==2.0.4
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.6
      - sphinxcontrib-serializinghtml==1.1.9
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-macos==2.14.0
      - termcolor==2.3.0
      - werkzeug==3.0.1
      - wrapt==1.14.1
prefix: /Users/egn/miniforge3/envs/TelescopeML
