name: TelescopeMLlinux
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3
  - python=3.9.18
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - absl-py==2.0.0
    - alabaster==0.7.13
    - anyio==4.0.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - astropy==5.3.4
    - asttokens==2.4.1
    - astunparse==1.6.3
    - async-lru==2.0.4
    - attrs==23.1.0
    - babel==2.13.1
    - beautifulsoup4==4.12.2
    - bleach==6.1.0
    - bokeh==3.3.1
    - cachetools==5.3.2
    - certifi==2023.11.17
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - comm==0.2.0
    - contourpy==1.2.0
    - cycler==0.12.1
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docutils==0.20.1
    - exceptiongroup==1.1.3
    - executing==2.0.1
    - fastjsonschema==2.19.0
    - flatbuffers==23.5.26
    - fonttools==4.45.0
    - fqdn==1.5.1
    - gast==0.5.4
    - google-auth==2.23.4
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.59.3
    - h5py==3.10.0
    - idna==3.4
    - imagesize==1.4.1
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.1
    - ipykernel==6.26.0
    - ipython==8.17.2
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.20.0
    - jsonschema-specifications==2023.11.1
    - jupyter-client==8.6.0
    - jupyter-core==5.5.0
    - jupyter-events==0.9.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.10.1
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.9
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.2
    - keras==2.14.0
    - kiwisolver==1.4.5
    - libclang==16.0.6
    - markdown==3.5.1
    - markupsafe==2.1.3
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - mistune==3.0.2
    - ml-dtypes==0.2.0
    - nbclient==0.9.0
    - nbconvert==7.11.0
    - nbformat==5.9.2
    - nest-asyncio==1.5.8
    - notebook-shim==0.2.3
    - numpy==1.26.1
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - overrides==7.4.0
    - packaging==23.2
    - pandas==2.1.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pillow==10.1.0
    - platformdirs==4.0.0
    - prometheus-client==0.19.0
    - prompt-toolkit==3.0.41
    - protobuf==4.25.1
    - psutil==5.9.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pyerfa==2.0.1.1
    - pygments==2.17.1
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - referencing==0.31.0
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.13.1
    - rsa==4.9
    - scikit-learn==1.3.0
    - scipy==1.11.1
    - seaborn==0.12.2
    - send2trash==1.8.2
    - six==1.16.0
    - sniffio==1.3.0
    - snowballstemmer==2.2.0
    - soupsieve==2.5
    - spectres==2.2.0
    - sphinx==7.2.6
    - sphinxcontrib-applehelp==1.0.7
    - sphinxcontrib-devhelp==1.0.5
    - sphinxcontrib-htmlhelp==2.0.4
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.6
    - sphinxcontrib-serializinghtml==1.1.9
    - stack-data==0.6.3
    - telescopeml==0.0.1
    - tensorboard==2.14.1
    - tensorboard-data-server==0.7.2
    - tensorflow==2.14.0
    - tensorflow-estimator==2.14.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==2.3.0
    - terminado==0.18.0
    - threadpoolctl==3.2.0
    - tinycss2==1.2.1
    - tomli==2.0.1
    - tornado==6.3.3
    - traitlets==5.13.0
    - types-python-dateutil==2.8.19.14
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - uri-template==1.3.0
    - urllib3==2.1.0
    - wcwidth==0.2.11
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.4
    - werkzeug==3.0.1
    - wrapt==1.14.1
    - xyzservices==2023.10.1
    - zipp==3.17.0
prefix: /home/egharibn/anaconda3/envs/TelescopeML
